# Generated by Django 5.2.5 on 2025-10-01 13:26

import base.models.snippets
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='intent',
            field=models.CharField(default='intent', max_length=700),
        ),
        migrations.AddField(
            model_name='homepage',
            name='methods',
            field=models.CharField(default='methods', max_length=700),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news',
            field=wagtail.fields.StreamField([('new', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (base.models.snippets.NewsItem,), {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vision',
            field=models.CharField(default='vision', max_length=700),
        ),
    ]
