# Generated by Django 5.2.5 on 2025-09-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='intent',
            field=models.CharField(default='intent', max_length=700),
        ),
        migrations.AddField(
            model_name='homepage',
            name='methods',
            field=models.CharField(default='methods', max_length=700),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vision',
            field=models.CharField(default='vision', max_length=700),
        ),
    ]
