# Generated by Django 5.2.5 on 2025-09-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
