# Generated by Django 5.2.5 on 2025-09-29 11:04

import base.models.snippets
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_body_homepage_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news',
            field=wagtail.fields.StreamField([('new', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (base.models.snippets.NewsItem,), {})}),
        ),
    ]
