# Generated by Django 5.2.5 on 2025-09-22 18:36

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_newsitem_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intent',
            field=models.CharField(default='intent', max_length=700),
        ),
        migrations.AddField(
            model_name='homepage',
            name='methods',
            field=models.CharField(default='methods', max_length=700),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vision',
            field=models.CharField(default='vision', max_length=700),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(),
        ),
    ]
