# Generated by Django 5.2.5 on 2025-09-29 09:26

import base.models.snippets
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', wagtail.fields.RichTextField()),
                ('citation', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True)),
                ('year', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('photos', wagtail.fields.StreamField([('photo', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('placed_at', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Publish date')),
                ('caption', models.CharField(max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('publications', wagtail.fields.StreamField([('publication', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (base.models.snippets.Publication,), {})})),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('scholars', wagtail.fields.StreamField([('scholar', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (base.models.snippets.Member,), {})})),
                ('masters', wagtail.fields.StreamField([('master', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (base.models.snippets.Member,), {})})),
                ('alumni', wagtail.fields.StreamField([('alumnus', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (base.models.snippets.Member,), {})})),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.member')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
