# Generated by Django 5.2.5 on 2025-09-27 16:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('PI', 'Principal Investigator'), ('PH', 'PhD Scholar'), ('MS', "Master's Student"), ('AL', 'Alumni')], default='PH', max_length=2)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
        ),
    ]
