# Generated by Django 5.2.5 on 2025-10-04 12:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
