# Generated by Django 5.2.5 on 2025-10-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_member_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_url', models.URLField(blank=True, verbose_name='X URL')),
                ('mailto', models.EmailField(blank=True, max_length=254, verbose_name='Contact email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
