# Generated by Django 5.2.5 on 2025-09-28 09:40

import base.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_gallery_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='placed_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='alumni',
            field=wagtail.fields.StreamField([('alumnus', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (base.models.Member,), {})}),
        ),
        migrations.AddField(
            model_name='team',
            name='masters',
            field=wagtail.fields.StreamField([('master', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (base.models.Member,), {})}),
        ),
        migrations.AddField(
            model_name='team',
            name='scholars',
            field=wagtail.fields.StreamField([('scholar', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (base.models.Member,), {})}),
        ),
    ]
