# Generated by Django 5.2.5 on 2025-09-28 09:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_member_placed_at_team_alumni_team_masters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=wagtail.fields.StreamField([('photo', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
        migrations.DeleteModel(
            name='GalleryPhoto',
        ),
    ]
