# Generated by Django 5.2.5 on 2025-10-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchentry',
            name='research_title',
        ),
    ]
