# Generated by Django 5.2.5 on 2025-09-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_researchentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchentry',
            old_name='header',
            new_name='citation',
        ),
        migrations.RemoveField(
            model_name='researchentry',
            name='body',
        ),
        migrations.AddField(
            model_name='researchentry',
            name='description',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchentry',
            name='research_title',
            field=models.CharField(default='Some Title', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchentry',
            name='url',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
